
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOLLAR EQUAL ID LQUESTION NUMBER RCARNET RCARRERA RCORREO RCREDITOS RDESCRIPCION RDPI REDAD RELEMENT RELEMENTS RESTADO RFECHA RHORA RITEM RMATERIA RNOMBRE RPASSWORD RQUESTION RTYPE STRINGinit : LQUESTION RELEMENTS RQUESTION list_elements LQUESTION DOLLAR RELEMENTS RQUESTIONlist_elements : list_elements elementlist_elements : elementelement : LQUESTION RELEMENT typeElement RQUESTION list_items LQUESTION DOLLAR RELEMENT RQUESTIONtypeElement : RTYPE EQUAL STRINGlist_items : list_items itemlist_items : itemitem : LQUESTION RITEM typeItem EQUAL valyeItem DOLLAR RQUESTIONvalyeItem : STRING\n                | NUMBERtypeItem : RCARNET\n                | RNOMBRE\n                | RDPI\n                | RCARRERA\n                | RCORREO\n                | RPASSWORD\n                | RCREDITOS\n                | REDAD\n                | RDESCRIPCION\n                | RMATERIA\n                | RFECHA\n                | RHORA\n                | RESTADO\n    '
    
_lr_action_items = {'LQUESTION':([0,4,6,7,10,14,18,19,24,45,47,],[2,5,9,-3,-2,17,23,-7,-6,-4,-8,]),'$end':([1,21,],[0,-1,]),'RELEMENTS':([2,13,],[3,16,]),'RQUESTION':([3,11,16,20,41,46,],[4,14,21,-5,45,47,]),'RELEMENT':([5,9,39,],[8,8,41,]),'RTYPE':([8,],[12,]),'DOLLAR':([9,23,42,43,44,],[13,39,46,-9,-10,]),'EQUAL':([12,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[15,40,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,]),'STRING':([15,40,],[20,43,]),'RITEM':([17,23,],[22,22,]),'RCARNET':([22,],[26,]),'RNOMBRE':([22,],[27,]),'RDPI':([22,],[28,]),'RCARRERA':([22,],[29,]),'RCORREO':([22,],[30,]),'RPASSWORD':([22,],[31,]),'RCREDITOS':([22,],[32,]),'REDAD':([22,],[33,]),'RDESCRIPCION':([22,],[34,]),'RMATERIA':([22,],[35,]),'RFECHA':([22,],[36,]),'RHORA':([22,],[37,]),'RESTADO':([22,],[38,]),'NUMBER':([40,],[44,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'list_elements':([4,],[6,]),'element':([4,6,],[7,10,]),'typeElement':([8,],[11,]),'list_items':([14,],[18,]),'item':([14,18,],[19,24,]),'typeItem':([22,],[25,]),'valyeItem':([40,],[42,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> LQUESTION RELEMENTS RQUESTION list_elements LQUESTION DOLLAR RELEMENTS RQUESTION','init',8,'p_init','Parser.py',4),
  ('list_elements -> list_elements element','list_elements',2,'p_list_elements','Parser.py',8),
  ('list_elements -> element','list_elements',1,'p_list_elements2','Parser.py',13),
  ('element -> LQUESTION RELEMENT typeElement RQUESTION list_items LQUESTION DOLLAR RELEMENT RQUESTION','element',9,'p_element','Parser.py',17),
  ('typeElement -> RTYPE EQUAL STRING','typeElement',3,'p_typeElement','Parser.py',21),
  ('list_items -> list_items item','list_items',2,'p_list_items','Parser.py',25),
  ('list_items -> item','list_items',1,'p_list_items2','Parser.py',30),
  ('item -> LQUESTION RITEM typeItem EQUAL valyeItem DOLLAR RQUESTION','item',7,'p_item','Parser.py',34),
  ('valyeItem -> STRING','valyeItem',1,'p_valueItem','Parser.py',38),
  ('valyeItem -> NUMBER','valyeItem',1,'p_valueItem','Parser.py',39),
  ('typeItem -> RCARNET','typeItem',1,'p_typeItem','Parser.py',43),
  ('typeItem -> RNOMBRE','typeItem',1,'p_typeItem','Parser.py',44),
  ('typeItem -> RDPI','typeItem',1,'p_typeItem','Parser.py',45),
  ('typeItem -> RCARRERA','typeItem',1,'p_typeItem','Parser.py',46),
  ('typeItem -> RCORREO','typeItem',1,'p_typeItem','Parser.py',47),
  ('typeItem -> RPASSWORD','typeItem',1,'p_typeItem','Parser.py',48),
  ('typeItem -> RCREDITOS','typeItem',1,'p_typeItem','Parser.py',49),
  ('typeItem -> REDAD','typeItem',1,'p_typeItem','Parser.py',50),
  ('typeItem -> RDESCRIPCION','typeItem',1,'p_typeItem','Parser.py',51),
  ('typeItem -> RMATERIA','typeItem',1,'p_typeItem','Parser.py',52),
  ('typeItem -> RFECHA','typeItem',1,'p_typeItem','Parser.py',53),
  ('typeItem -> RHORA','typeItem',1,'p_typeItem','Parser.py',54),
  ('typeItem -> RESTADO','typeItem',1,'p_typeItem','Parser.py',55),
]
